---
- name: WordPress Installed?
  command: wp core is-installed {{ project.multisite.enabled | default(false) | ternary('--network', '') }}
  args:
    chdir: "{{ deploy_helper.current_path }}"
  register: wp_installed
  changed_when: false
  failed_when: wp_installed.stderr != ""

- name: Update WP database
  command: wp core update-db
  args:
    chdir: "{{ deploy_helper.current_path }}"
  when: wp_installed | success and not project.multisite.enabled | default(false)

- name: Warn about updating network database.
  debug:
    msg: "Updating the network database could take a long time with a large number of sites."
  when: wp_installed | success and project.multisite.enabled | default(false)

- name: Update WP network database
  command: wp core update-db --network
  args:
    chdir: "{{ deploy_helper.current_path }}"
  when: wp_installed | success and project.multisite.enabled | default(false)

- name: Get WP theme template root
  command: wp option get template_root
  args:
    chdir: "{{ deploy_helper.current_path }}"
  register: wp_template_root
  changed_when: false
  failed_when: wp_template_root.stderr != ""
  when: wp_installed | success

- name: Update WP theme paths
  command: wp option set {{ item }} {{ deploy_helper.new_release_path }}/web/wp/wp-content/themes
  args:
    chdir: "{{ deploy_helper.current_path }}"
  when: wp_installed | success and wp_template_root != '/themes' and wp_template_root != ''
  with_items:
    - stylesheet_root
    - template_root

- name: Reload php-fpm
  shell: sudo service php7.1-fpm reload
  args:
    warn: false
